In [4]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests

In [5]:
html = requests.get("https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page").text

soup = BeautifulSoup(html, "html.parser")

links = []
for link in soup.find("div", {"id": "faq2021"}).find_all("a"):
    if link["title"] == "High Volume For-Hire Vehicle Trip Records":
        links.append(link["href"])

In [6]:
links

['https://nyc-tlc.s3.amazonaws.com/trip+data/fhvhv_tripdata_2021-01.csv',
 'https://nyc-tlc.s3.amazonaws.com/trip+data/fhvhv_tripdata_2021-02.csv',
 'https://nyc-tlc.s3.amazonaws.com/trip+data/fhvhv_tripdata_2021-03.csv',
 'https://nyc-tlc.s3.amazonaws.com/trip+data/fhvhv_tripdata_2021-04.csv',
 'https://nyc-tlc.s3.amazonaws.com/trip+data/fhvhv_tripdata_2021-05.csv',
 'https://nyc-tlc.s3.amazonaws.com/trip+data/fhvhv_tripdata_2021-06.csv',
 'https://nyc-tlc.s3.amazonaws.com/trip+data/fhvhv_tripdata_2021-07.csv']

In [7]:
dfs = []
for link in links:
    dfs.append(pd.read_csv(link))

In [8]:
dfs

[         hvfhs_license_num dispatching_base_num      pickup_datetime  \
 0                   HV0003               B02682  2021-01-01 00:33:44
 1                   HV0003               B02682  2021-01-01 00:55:19
 2                   HV0003               B02764  2021-01-01 00:23:56
 3                   HV0003               B02764  2021-01-01 00:42:51
 4                   HV0003               B02764  2021-01-01 00:48:14
 ...                    ...                  ...                  ...
 11908463            HV0003               B02765  2021-01-31 23:25:40
 11908464            HV0003               B02872  2021-01-31 23:29:31
 11908465            HV0003               B02872  2021-01-31 23:49:32
 11908466            HV0003               B02764  2021-01-31 23:09:29
 11908467            HV0003               B02764  2021-01-31 23:28:33

              dropoff_datetime  PULocationID  DOLocationID  SR_Flag
 0         2021-01-01 00:49:07           230           166      NaN
 1         2021-01-01 01:18:21           152           167      NaN
 2         2021-01-01 00:38:05           233           142      NaN
 3         2021-01-01 00:45:50           142           143      NaN
 4         2021-01-01 01:08:42           143            78      NaN
 ...                       ...           ...           ...      ...
 11908463  2021-01-31 23:40:10            89            71      NaN
 11908464  2021-01-31 23:47:44           182           167      NaN
 11908465  2021-02-01 00:04:36           167           169      NaN
 11908466  2021-01-31 23:27:46           188            37      NaN
 11908467  2021-01-31 23:56:36            37             4      NaN

 [11908468 rows x 7 columns],
          hvfhs_license_num dispatching_base_num      pickup_datetime  \
 0                   HV0003               B02764  2021-02-01 00:10:40
 1                   HV0003               B02764  2021-02-01 00:27:23
 2                   HV0005               B02510  2021-02-01 00:28:38
 3                   HV0005               B02510  2021-02-01 00:43:37
 4                   HV0003               B02872  2021-02-01 00:08:42
 ...                    ...                  ...                  ...
 11613937            HV0003               B02682  2021-02-28 23:52:56
 11613938            HV0003               B02764  2021-02-28 23:14:28
 11613939            HV0003               B02764  2021-02-28 23:42:04
 11613940            HV0003               B02764  2021-02-28 23:08:23
 11613941            HV0003               B02764  2021-02-28 23:17:09

              dropoff_datetime  PULocationID  DOLocationID  SR_Flag
 0         2021-02-01 00:21:09            35            39      NaN
 1         2021-02-01 00:44:01            39            35      NaN
 2         2021-02-01 00:38:27            39            91      NaN
 3         2021-02-01 01:23:20            91           228      NaN
 4         2021-02-01 00:17:57           126           250      NaN
 ...                       ...           ...           ...      ...
 11613937  2021-03-01 00:26:18            21            92      NaN
 11613938  2021-02-28 23:37:55           148           228      NaN
 11613939  2021-03-01 00:05:06           228            89      NaN
 11613940  2021-02-28 23:12:34            10           205      NaN
 11613941  2021-02-28 23:29:53            10           216      NaN

 [11613942 rows x 7 columns],
          hvfhs_license_num dispatching_base_num      pickup_datetime  \
 0                   HV0003               B02764  2021-03-01 00:07:07
 1                   HV0003               B02764  2021-03-01 00:17:00
 2                   HV0003               B02764  2021-03-01 00:51:29
 3                   HV0003               B02835  2021-03-01 00:07:16
 4                   HV0003               B02835  2021-03-01 00:19:09
 ...                    ...                  ...                  ...
 14227388            HV0003               B02864  2021-03-31 23:33:05
 14227389            HV0003               B02864  2021-03-31 23:41:53
 14227390            HV0003               B02764  2021-03-31 23:06:29
 14227391            HV0003               B02764  2021-03-31 23:38:44
 14227392            HV0003               B02764  2021-03-31 23:47:29

              dropoff_datetime  PULocationID  DOLocationID  SR_Flag
 0         2021-03-01 00:13:56            56            82      NaN
 1         2021-03-01 00:38:08            82           100      NaN
 2         2021-03-01 01:06:02           237           249      NaN
 3         2021-03-01 00:12:35           136           235      NaN
 4         2021-03-01 00:27:52           235           153      NaN
 ...                       ...           ...           ...      ...
 14227388  2021-03-31 23:38:17           220           241      NaN
 14227389  2021-03-31 23:57:50           136            74      NaN
 14227390  2021-03-31 23:20:13           161           145      NaN
 14227391  2021-03-31 23:44:04           233           107      NaN
 14227392  2021-04-01 00:00:23           137           146      NaN

 [14227393 rows x 7 columns],
          hvfhs_license_num dispatching_base_num      pickup_datetime  \
 0                   HV0003               B02764  2021-04-01 00:10:56
 1                   HV0003               B02764  2021-04-01 00:32:36
 2                   HV0003               B02764  2021-04-01 00:47:49
 3                   HV0003               B02878  2021-04-01 00:12:39
 4                   HV0003               B02878  2021-04-01 00:26:47
 ...                    ...                  ...                  ...
 14111366            HV0005               B02510  2021-04-30 23:07:52
 14111367            HV0005               B02510  2021-04-30 23:23:04
 14111368            HV0005               B02510  2021-04-30 23:46:08
 14111369            HV0003               B02764  2021-04-30 23:11:32
 14111370            HV0003               B02764  2021-04-30 23:26:42

              dropoff_datetime  PULocationID  DOLocationID  SR_Flag
 0         2021-04-01 00:26:15            51           254      NaN
 1         2021-04-01 00:42:04           240           248      NaN
 2         2021-04-01 00:56:14            60           167      NaN
 3         2021-04-01 00:22:15           124            39      NaN
 4         2021-04-01 00:51:53            39           195      NaN
 ...                       ...           ...           ...      ...
 14111366  2021-04-30 23:11:46           125           249      NaN
 14111367  2021-04-30 23:44:46           158           112      NaN
 14111368  2021-05-01 00:03:42           112            90      NaN
 14111369  2021-04-30 23:21:07           237           239      NaN
 14111370  2021-04-30 23:52:43           238           265      NaN

 [14111371 rows x 7 columns],
          hvfhs_license_num dispatching_base_num      pickup_datetime  \
 0                   HV0003               B02764  2021-05-01 00:07:26
 1                   HV0003               B02764  2021-05-01 00:17:47
 2                   HV0003               B02764  2021-05-01 00:47:11
 3                   HV0003               B02764  2021-05-01 00:59:29
 4                   HV0003               B02764  2021-05-01 00:16:21
 ...                    ...                  ...                  ...
 14719166            HV0003               B02764  2021-05-31 23:41:24
 14719167            HV0003               B02764  2021-05-31 23:56:34
 14719168            HV0003               B02764  2021-05-31 23:35:27
 14719169            HV0003               B02764  2021-05-31 23:52:48
 14719170            HV0003               B02765  2021-05-31 23:52:10

              dropoff_datetime  PULocationID  DOLocationID  SR_Flag
 0         2021-05-01 00:14:44           246           234      NaN
 1         2021-05-01 00:31:24           113           238      NaN
 2         2021-05-01 00:55:24           236           262      NaN
 3         2021-05-01 01:12:06           262           143      NaN
 4         2021-05-01 00:59:12           263           265      NaN
 ...                       ...           ...           ...      ...
 14719166  2021-05-31 23:51:15           147            74      NaN
 14719167  2021-06-01 00:08:34            74            42      NaN
 14719168  2021-05-31 23:45:59           130            10      NaN
 14719169  2021-05-31 23:57:33           218            10      NaN
 14719170  2021-06-01 00:46:45           138           265      NaN

 [14719171 rows x 7 columns],
          hvfhs_license_num dispatching_base_num      pickup_datetime  \
 0                   HV0003               B02764  2021-06-01 00:02:41
 1                   HV0003               B02764  2021-06-01 00:16:16
 2                   HV0003               B02764  2021-06-01 00:27:01
 3                   HV0003               B02764  2021-06-01 00:46:08
 4                   HV0005               B02510  2021-06-01 00:45:42
 ...                    ...                  ...                  ...
 14961887            HV0003               B02512  2021-06-30 23:30:49
 14961888            HV0003               B02512  2021-06-30 23:52:25
 14961889            HV0005               B02510  2021-06-30 23:39:48
 14961890            HV0003               B02764  2021-06-30 23:09:30
 14961891            HV0003               B02764  2021-06-30 23:41:07

              dropoff_datetime  PULocationID  DOLocationID  SR_Flag
 0         2021-06-01 00:07:46           174            18      NaN
 1         2021-06-01 00:21:14            32           254      NaN
 2         2021-06-01 00:42:11           240           127      NaN
 3         2021-06-01 00:53:45           127           235      NaN
 4         2021-06-01 01:03:33           144           146      NaN
 ...                       ...           ...           ...      ...
 14961887  2021-06-30 23:46:26           162           249      NaN
 14961888  2021-07-01 00:16:00            68            25      NaN
 14961889  2021-06-30 23:51:02           162           249      NaN
 14961890  2021-06-30 23:24:21           261           137      NaN
 14961891  2021-07-01 00:10:23            33           201      NaN

 [14961892 rows x 7 columns],
          hvfhs_license_num dispatching_base_num      pickup_datetime  \
 0                   HV0003               B02875  2021-07-01 00:10:28
 1                   HV0003               B02875  2021-07-01 00:30:11
 2                   HV0003               B02878  2021-07-01 00:36:42
 3                   HV0003               B02878  2021-07-01 00:50:59
 4                   HV0003               B02764  2021-07-01 00:14:45
 ...                    ...                  ...                  ...
 15027169            HV0003               B02764  2021-07-31 23:16:46
 15027170            HV0003               B02764  2021-07-31 23:39:35
 15027171            HV0003               B02764  2021-07-31 23:57:07
 15027172            HV0003               B02764  2021-07-31 23:12:51
 15027173            HV0003               B02764  2021-07-31 23:41:29

              dropoff_datetime  PULocationID  DOLocationID  SR_Flag
 0         2021-07-01 00:17:53            82           157      NaN
 1         2021-07-01 00:36:37            82            95      NaN
 2         2021-07-01 00:46:03            68           239      NaN
 3         2021-07-01 01:05:03           239           224      NaN
 4         2021-07-01 00:31:36           188            39      NaN
 ...                       ...           ...           ...      ...
 15027169  2021-07-31 23:33:10           164           125      NaN
 15027170  2021-07-31 23:50:08           211           234      NaN
 15027171  2021-08-01 00:14:04           164           163      NaN
 15027172  2021-07-31 23:20:50           161           263      NaN
 15027173  2021-07-31 23:54:30           107            79      NaN

 [15027174 rows x 7 columns]]